cargo publish integration into action

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,7 +2,7 @@ name: Release
 
 on:
   release:
-    types: [ published ]
+    types: [ created ]
 
 jobs:
   release:
@@ -14,6 +14,14 @@ jobs:
     steps:
       - name: Checkout sources
         uses: actions/checkout@v3
+
+      - name: Verify crate version matches release tag
+        run: |
+          CRATE_VERSION=$(grep -m1 '^version' Cargo.toml | cut -d '"' -f 2)
+          if [[ "v$CRATE_VERSION" != "${{ github.ref_name }}" ]]; then
+            echo "Error: Cargo.toml version ($CRATE_VERSION) doesn't match release tag (${{ github.ref_name }})"
+            exit 1
+          fi
 
       - name: Install stable toolchain
         uses: actions-rs/toolchain@v1
@@ -33,6 +41,12 @@ jobs:
           command: build
           args: --release
       
+      - name: Publish to crates.io
+        env:
+          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
+        run: |
+          cargo publish --verbose
+      
       - name: Create package
         working-directory: ${{ runner.workspace }}/Loss/
         id: package
@@ -42,7 +56,7 @@ jobs:
           cp target/release/loss release/
           cp README.md release/
           cp LICENSE release/
-          PACKAGE_NAME=loss-${GITHUB_REF#refs/tags/}-${{ matrix.os }}.tar.gz
+          PACKAGE_NAME=loss-${{ github.ref_name }}-${{ matrix.os }}.tar.gz
           tar -czvf $PACKAGE_NAME -C release .
           echo "name=${PACKAGE_NAME}" >> $GITHUB_OUTPUT
       
@@ -55,3 +69,9 @@ jobs:
           asset_path: ${{ steps.package.outputs.name }}
           asset_name: ${{ steps.package.outputs.name }}
           asset_content_type: application/gzip
+      
+      - name: Publish draft release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          gh release edit ${{ github.ref_name }} --draft=false
